---
galaxy_info:
  author: Mitsuru Nakakawaji
  description: Build docker swarm mode and drbd9+drbdmanage cluster on Centos 7.x.
  company: Procube Co.,Ltd.
  license: MIT
  min_ansible_version: 2.5
  platforms:
  - name: EL
    versions:
    - "7"
  galaxy_tags:
    - drbd
    - docker
