- name: build mother VM
  hosts: mother
  become: True
  vars_files:
    - ../config/vars/main.yml

  roles:
    - base
    - iptables
    - vagrant
    - ntp-client
    - role: pip-venv
      become_user: "{{ administrator }}"
    - role: ansible
      become_user: "{{ administrator }}"
    - role: aws
      become_user: "{{ administrator }}"
    - reboot
