---
- name: compose containers
  hosts: targets
  gather_facts: False
  become: false
  tags: compose-containers

  tasks:
  - name: load variables from parent vars directory
    include_vars: "{{ item }}"
    with_fileglob: "../../config/vars/*.yml"

  - name: add host for delegator
    add_host:
      hostname: "dlg-{{ item }}"
      ansible_connection: local
      enviroment:
        DOCKER_HOST: "tcp://{{ item }}:2376"
        DOCKER_TLS_VERIFY: 1
      ansible_python_interpreter: "../../ansible/bin/python"
    with_items: "{{ play_hosts }}"
    changed_when: False

  - name: compose down containers
    delegate_to: "dlg-{{ inventory_hostname }}"
    docker_service:
      project_src: "../../hosts.d/{{ inventory_hostname }}/{{ item }}"
      state: absent
      remove_images: all
      remove_volumes: True
      docker_host: "tcp://{{ inventory_hostname }}:2376"
      timeout: 120
      tls: yes
      cacert_path: "../../.docker/ca.pem"
      cert_path: "../../.docker/cert.pem"
      key_path:  "../../.docker/key.pem"
    with_items: "{{ services | default([])}}"
    when: swarm_master is not defined

  - name: undeploy service stacks
    delegate_to: "dlg-{{ inventory_hostname }}"
    shell: "docker stack rm {{ item }}"
    args:
      chdir: "../../hosts.d/{{ inventory_hostname }}/{{ item }}"
    with_items: "{{ services | default([])}}"
    when: swarm_master is defined

  - name: "delete host directory"
    connection: local
    file:
      path: "../../hosts.d/{{ inventory_hostname }}"
      state: absent
