---
- name: setup self private_key
  become: false
  copy:
    src: "../vagrant/.vagrant/machines/{{mother_name}}/virtualbox/private_key"
    dest: ~/.ssh/id_vagrant
    mode: 0600
- name: set .ssh/config
  become: false
  blockinfile:
    dest: "~/.ssh/config"
    marker: "# {mark} ANSIBLE MANAGED BLOCK vagrant {{ inventory_hostname }}"
    insertafter: BOF
    state: present
    create: yes
    mode: 0644
    block: |
      Host {{ inventory_hostname }}
        User vagrant
        IdentityFile ~/.ssh/id_vagrant
        StrictHostKeyChecking no
- name: setup synctime command
  become: false
  blockinfile:
    dest: ~/.bashrc
    insertafter: BOF
    state: present
    block: |
      alias synctime='sudo systemctl restart chronyd && sudo chronyc makestep'
      synctime
    marker: "# {mark} ANSIBLE MANAGED BLOCK synctime command"
