---
  - name: "Build hosts file"
    become: True
    blockinfile:
      dest: /etc/hosts
      insertafter: BOF
      state: "present"
      block: "{{ hostvars[item].private_ip }} {{ item }}{% if item == (manager_host | default(''))%} {{ registry_fqdn }}{% endif %}"
      marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
    with_items: "{{ groups['targets'] }}"
