---
# - name: install pyOpenSSL
#   pip:
#     name: pyOpenSSL
#     state: present
- name: create work directory for extra attribute file, csr
  become: False
  file:
    path: "cawork"
    state: directory
    mode: 0775
# - name: CA private key
#   shell: openssl genrsa -aes256 -out /etc/pki/CA/private/cakey.pem 4096
#   args:
#     creates: /etc/pki/CA/private/cakey.pem
- name: setup extra attribute file
  become: False
  copy:
    src: extfile.cnf
    dest: cawork/extfile-ca.cnf
- name: CA CSR
  become: False
  shell: |
    openssl req -batch -new -newkey rsa:4096 -nodes -sha256 \
      -subj '/E={{ ca_EMail }}/C={{ ca_C }}/ST={{ ca_ST }}/L={{ ca_L }}/O={{ ca_O }}/OU={{ ca_OU }}/CN={{ ca_CN }}' \
      -keyout cawork/cakey.pem \
      -out cawork/ca-ca.csr
  args:
    creates: cawork/ca-ca.csr
- name: CA certificate
  shell: |
    openssl x509 -req  -days "{{ ca_valid_in }}" -sha256 -in cawork/ca-ca.csr \
      -signkey cawork/cakey.pem \
      -out cawork/cacert.pem \
      -extfile cawork/extfile-ca.cnf
  args:
    creates: "cawork/cacert.pem"
- name: fetch cert file into local
  tags: signed
  fetch:
    src:  cawork/cacert.pem
    fail_on_missing: yes
    flat: yes
    dest: /var/tmp/mother/cacert.pem
