---
- name: "setup bakckup directory"
  file:
    path: "~/backup"
    state: directory
    mode: 0755
- name: add backup script
  become_user: root
  copy:
    src: site-backup.sh
    dest: /usr/bin/site-backup.sh
    mode: 0755
- name: add backup service
  become_user: root
  copy:
    src: "{{item}}"
    dest: /usr/lib/systemd/system
    mode: 0644
  with_items:
    - backup@.service
    - backup@.timer
- name: enable and start backup timer service
  become_user: root
  service:
    name: "backup@{{ builder }}.timer"
    enabled: yes
  notify: require reboot

- name: "backup script template"
  copy:
    src: "{{ item }}"
    dest: "~/site-builder/"
    mode: 0644
  with_items:
    - doBackup.sh
    - doRestore.sh
