---
- name: load config from git
  import_tasks: load-config-git.yml
  when: git is defined

- name: copy config
  copy:
    src: "../config"
    dest: "./"
  when: git is not defined

- import_tasks: registry.yml

- import_tasks: install-builder.yml
  tags: bulder

- import_tasks: install-backup-tools.yml
  tags: backup-tools
