---
- name: load config from git
  tags: copy-config
  import_tasks: load-config-git.yml
  when: git is defined

- name: copy config create dir
  tags: copy-config
  file:
    dest: "~/config"
    state: directory
  when: git is not defined and site_root is not defined

- name: copy config
  tags: copy-config
  copy:
    src: "../../site-builder/../"
    dest: "~/config"
  when: git is not defined and site_root is not defined

- name: link config
  tags: copy-config
  file:
    src: "{{ site_root }}"
    dest: "~/config"
    state: link
  when: git is not defined and site_root is defined


- name: import roles
  tags: import-roles
  copy:
    src: "roles"
    dest: "~/site-builder/"
  when: import_roles | default(false)

- import_tasks: install-builder.yml
  tags: bulder

- import_tasks: install-backup-tools.yml
  tags: backup-tools
