{% raw %}
- name: Destroy VPC
  hosts: localhost
  connection: local
  tasks:
  - name: Delete subnets
    ec2_vpc_subnet:
      state: absent
      vpc_id: "{{ item.id }}"
      cidr: "{{ item.cidr }}"
    with_items:
{% endraw %}
{% for result in vpc_info.results %}
      - id: {{ result.vpc.id }}
        cidr: {{ result.vpc.cidr_block }}
{% endfor %}
{% raw %}
  - name: Delete VPC gateway
    ec2_vpc_igw:
      vpc_id: "{{ item }}"
{% endraw %}
      region: "{{ aws.region }}"
      state: absent
    with_items:
{% for result in vpc_info.results %}
      - {{ result.vpc.id }}
{% endfor %}
{% raw %}
  - name: Delete VPC
    ec2_vpc_net:
      state: absent
      name: "{{ item.name }}"
      cidr_block: "{{ item.cidr }}"
{% endraw %}
      region: "{{ aws.region }}"
    with_items:
{% for result in vpc_info.results %}
      - name: {{ result.item.name }}
        cidr: {{ result.vpc.cidr_block }}
{% endfor %}
