---
- name: install ansible and docker-py
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    state: present
    virtualenv: "~/ansible"
  with_items:
    - name: urllib3
    - name: requests
    - name: ansible
    - name: docker
    # for lookup('dig', ..)
    - name: dnspython
- name: "setup ansible configuration files"
  template:
    src: ansible.cfg.j2
    dest: "~/.ansible.cfg"
