---
- name: install ansible and docker-py
  pip:
    name: "{{ item }}"
    state: present
    virtualenv: "~/ansible"
  with_items:
    - urllib3
    - requests
    - ansible
    - docker-py
- name: "setup ansible configuration files"
  template:
    src: ansible.cfg.j2
    dest: "~/.ansible.cfg"
