---
- name: reboot
  shell: "sleep 2 && {{ reboot_command | default('reboot')}}"
  async: 1
  poll: 0
  tags: reboot
  changed_when: false
  listen: require reboot
  when: not ((skip_reboot | default(False)) or check_mode)
  register: reboot
- name: wait for connectable
  wait_for_connection:
    delay: 30
  tags: reboot
  listen: require reboot
  when: reboot is not skipped and reboot_command is not defined
