---
- name: setup docker ce repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644
- name: install docker package
  yum:
    name: docker-ce
    state: present
- name: add docker group
  group:
    name: docker
    state: present
- name: allow local connection to administrator
  user:
    name: "{{ builder }}"
    append: True
    groups: docker
  when: builder is defined
- name: insert allow api port rule into iptables (no internal network)
  blockinfile:
    dest: /etc/sysconfig/iptables
    insertafter: -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
    block: |
      -A INPUT -p tcp -s {{ item }} -m state --state NEW -m multiport --dport 2376 -j ACCEPT
    marker: "# {mark} ANSIBLE MANAGED BLOCK for docker api {{ item }}"
  with_items: "{{ansible_play_batch | map('extract', hostvars, 'private_ip') | list}}"
  when: internal_net_addr is not defined
  notify: require reboot
- name: insert allow api port rule into iptables for internal network
  blockinfile:
    dest: /etc/sysconfig/iptables
    insertafter: -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
    block: |
      -A INPUT -p tcp -s {{ internal_net_addr }}/{{ internal_net_cidr }} -m state --state NEW -m multiport --dport 2376 -j ACCEPT
    marker: "# {mark} ANSIBLE MANAGED BLOCK for docker api for internal network"
  when: internal_net_addr is defined
  notify: require reboot
- name: insert allow api port rule into iptables for docker container
  blockinfile:
    dest: /etc/sysconfig/iptables
    insertafter: -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
    block: |
      -A INPUT -p tcp -s 172.16.0.0/12 -m state --state NEW -m multiport --dport 2376 -j ACCEPT
    marker: "# {mark} ANSIBLE MANAGED BLOCK for docker api"
  notify: require reboot
- name: create directory /etc/docker
  file:
    dest: "/etc/docker"
    state: directory
    mode: 0700
    owner: root
    group: root
- name: setup certificate for remote api
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
- name: insert allow swarm port rule into iptables (no internal network)
  blockinfile:
    dest: /etc/sysconfig/iptables
    insertafter: -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
    block: |
      -A INPUT -p tcp -s {{ item }} -m state --state NEW -m multiport --dport 2377,7946 -j ACCEPT
      -A INPUT -p udp -s {{ item }} -m state --state NEW -m multiport --dport 7946,4789 -j ACCEPT
    marker: "# {mark} ANSIBLE MANAGED BLOCK for swarm {{ item }}"
  with_items: "{{ansible_play_batch | map('extract', hostvars, 'private_ip') | list}}"
  when: internal_net_addr is not defined
  notify: require reboot
- name: insert allow swarm port rule into iptables for internal network
  blockinfile:
    dest: /etc/sysconfig/iptables
    insertafter: -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
    block: |
      -A INPUT -p tcp -s {{ internal_net_addr }}/{{ internal_net_cidr }} -m state --state NEW -m multiport --dport 2377,7946 -j ACCEPT
      -A INPUT -p udp -s {{ internal_net_addr }}/{{ internal_net_cidr }} -m state --state NEW -m multiport --dport 7946,4789 -j ACCEPT
    marker: "# {mark} ANSIBLE MANAGED BLOCK for swarm"
  when: internal_net_addr is defined
  notify: require reboot
- name: "gather if gcp or not"
  stat: path=/etc/sysctl.d/11-gce-network-security.conf
  register: gcp_cfg
- name: "set kernel parameter for ip forwarding at gcp instance"
  lineinfile:
    regexp: "{{ item }}=[01]"
    line: "{{ item }}=1"
    path: /etc/sysctl.d/11-gce-network-security.conf
    state: present
  with_items:
    - net.ipv4.ip_forward
    - net.ipv4.conf.all.send_redirects
    - net.ipv4.conf.default.send_redirects
  notify: require reboot
  when: gcp_cfg.stat.exists
- name: add config RestartSec - create dir
  file:
    dest: /usr/lib/systemd/system/docker.service.d
    state: directory
    mode: 0700
    owner: root
    group: root
- name: add config RestartSec - override.conf
  copy:
    dest: /usr/lib/systemd/system/docker.service.d/override.conf
    content: |
      [Service]
      RestartSec=15s
      EnvironmentFile=-/etc/environment
    mode: 0700
    owner: root
    group: root
- name: enable service
  service: name=docker enabled=yes
  notify: require reboot
