---
# common utiility packages.
- name: Disable yum-fastestmirror
  lineinfile: >
    dest="/etc/yum/pluginconf.d/fastestmirror.conf"
    line="enabled=0"
    state=present
    regexp="^#?enabled="
    insertafter=EOF
    create=yes
    owner=root group=root mode=0644
- name: install packages
  yum:
    state: present
    name:
      - bridge-utils
      - wget
      - vim
      - unzip
      - telnet
      - sysstat
      - strace
      - tcpdump
      - lsof
- name: disable selinux
  selinux: >
    state=disabled
  notify: require reboot
- name: enable services
  service: "name={{ item }} enabled=yes"
  with_items:
    - sysstat
  notify: require reboot
- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"
- name: "gather if aws or not"
  stat: path=/etc/cloud
  register: cloud_cfg
- name: preserve hostname setting for ec2
  lineinfile:
    line: "preserve_hostname: true"
    path: /etc/cloud/cloud.cfg
    state: present
  when: cloud_cfg.stat.exists
- name: "set timezone"
  timezone:
    name: "{{ timezone }}"
  when: timezone is defined
- name: "gather available locales"
  shell: localectl list-locales
  register: locales
  changed_when: False
- name: "set locale"
  shell: "localedef -f UTF-8 -i {{ locale }} {{ locale }}"
  when: locale is defined and not (locale in locales.stdout_lines)
# setting up sshd parameters
- name: disable Password Authentication for sshd
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    insertafter: "^#PasswordAuthentication"
    line: "PasswordAuthentication no"
- name: disable Challenge Response Authentication for sshd
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^ChallengeResponseAuthentication"
    insertafter: "^#ChallengeResponseAuthentication"
    line: "ChallengeResponseAuthentication no"
