---
- hosts: managers
  connection: local

  tasks:
  - name: load variables from parent vars directory
    include_vars: "{{ item }}"
    with_fileglob: "../../vars/*.yml"
  - name: set ansible_python_interpreter
    set_fact:
      ansible_python_interpreter: "/home/vagrant/ansible/bin/python"
  - name: construct VPC
    ec2_vpc_net:
      name: "{{ item.name }}"
      state: present
      cidr_block: "{{ item.cidr }}"
      region: "{{ aws.region }}"
    register:  vpc_info
    with_items: "{{aws.vpc}}"
  - name: Setup internet gateway for VPC
    ec2_vpc_igw:
      vpc_id: "{{ item.vpc.id }}"
      region: "{{ aws.region }}"
      state: present
      tags:
        Name: gateway for {{ item.item.name }}
    with_items: "{{vpc_info.results | selectattr('item.with_igw', 'defined') | list}}"
    register: igw
  - name: Setup subnet for VPC
    ec2_vpc_subnet:
      state: present
      az: "{{ aws.az1 }}"
      vpc_id: "{{ item.vpc.id }}"
      cidr: "{{ item.item.cidr }}"
      resource_tags:
        Name: "subnet-{{ item.item.name }}"
    with_items: "{{vpc_info.results}}"
    register: subnet
  - name: gather default root table facts
    ec2_vpc_route_table_facts:
      region: "{{ aws.region }}"
      filters:
        vpc-id: "{{item.item.vpc.id}}"
    with_items: "{{subnet.results}}"
    register: rtb_info
  - name: Set up public subnet route table
    ec2_vpc_route_table:
      vpc_id: "{{ item.item.item.vpc.id }}"
      route_table_id: "{{ item.route_tables[0].id }}"
      region: "{{ aws.region }}"
      lookup: id
      tags:
        Name: Public for subnet
      subnets:
        - "{{ item.item.subnet.id }}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{ (igw.results | selectattr('item.item.name', 'equalto', item.item.item.item.name) | list)[0].gateway_id }}"
    with_items: "{{rtb_info.results}}"
  - name: build EC2 instance
    ec2:
      region: "{{ aws.region }}"
      vpc_subnet_id: "{{ (subnet.results | selectattr('item.item.name', 'equalto', hostvars[item].vpc) | list)[0].subnet.id }}"
      image: "{{ aws.image_id }}"
      instance_type: "{{ hostvars[item].host_size }}"
      key_name: awsroot
      volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: 8
          delete_on_termination: true
      assign_public_ip: true
      wait: yes
      group: default
      private_ip: "{{hostvars[item].private_ip | default(hostvars[item].ansible_host)}}"
      termination_protection: no
      count_tag:
        Name: "{{ item }}"
      exact_count: 1
      # state: running
      instance_tags:
        Name: "{{item}}"
    with_items: "{{ groups['targets'] }}"
    register: ec2
  - debug: var=ec2
  - name: Find ENIs created for Edge instances
    ec2_eni_facts:
      region: "{{ aws.region }}"
      filters:
        attachment.instance-id: "{{ item.tagged_instances[0].id }}"
    with_items: "{{ ec2.results }}"
    when: hostvars[item.item].secondary_ip is defined
    register: secondary_ip_enis
  - debug: var=secondary_ip_enis
  - name: assign secondary ip
    ec2_eni:
      region: "{{ aws.region }}"
      subnet_id: "{{ (secondary_ip_enis.results | selectattr('item.item', 'equalto', item) | list)[0].network_interfaces[0].subnet_id }}"
      eni_id: "{{ (secondary_ip_enis.results | selectattr('item.item', 'equalto', item) | list)[0].network_interfaces[0].network_interface_id }}"
      state: present
      secondary_private_ip_addresses:
        - "{{ hostvars[item].secondary_ip }}"
    with_items: "{{ ec2.results | map(attribute='item') | list}}"
    when: hostvars[item].secondary_ip is defined
  - name: associate the elastic IP with instances
    ec2_eip:
      device_id: "{{ item.tagged_instances[0].id }}"
      in_vpc: yes
      release_on_disassociation: yes
      region: "{{ aws.region }}"
      public_ip: "{{ hostvars[item.item].eip }}"
    register: eip
    with_items: "{{ ec2.results }}"
    when: hostvars[item.item].eip is defined
  - name: "Install destruct VPC playbook"
    template:
      src: ../aws/destroy_vpc.j2.yml
      dest: ~/.resource/destroy_vpc.yml
      mode: 0644
  - name: "Install stop all ec2 instance playbook"
    template:
      src: ../aws/stop_ec2.j2.yml
      dest: ~/.resource/stop_ec2.yml
      mode: 0644
  - name: "Install connect aws playbook"
    template:
      src: ../aws/connect_aws.j2.yml
      dest: ~/.resource/connect_aws.yml
      mode: 0644
