- name: build mother VM
  hosts: all
  become: True

  roles:
    - vars
    - base
    - iptables
    - vagrant
    - role: ntp-client
      when: ntp_servers is defined
    - role: pip-venv
      become_user: "{{ administrator }}"
    - role: ansible
      become_user: "{{ administrator }}"
    - role: aws
      become_user: "{{ administrator }}"
      aws_builder: True
    - role: reboot
      tags: reboot
