- name: build mother VM
  hosts: all
  become: True

  roles:
    - vars
    - base
    - iptables
    - vagrant
    - role: ntp-client
      when: ntp_servers is defined
    - role: pip-venv
      become_user: "{{ administrator }}"
    - role: ansible
      become_user: "{{ administrator }}"
    - role: cloud
      become_user: "{{ administrator }}"
      when: cloud_platform is defined
    - role: reboot
      when: not (skip_reboot | default(False))
