---
- name: setup docker host servers
  hosts: targets
  become: True
  tags: setup-hosts

  roles:
    - vars
    - base
    - hostsfile
    - role: ntp-client
      when: ntp_servers is defined
    - iptables
    - role: internal-network
      when: internal_net_if is defined
    - role: auxiliary-networks
      when: (config_auxiliary_networks | default(False)) and auxiliary_networks is defined
      tags: auxiliary-networks
    - role: users
      when: users is defined
    - strict-source-ip
    - reboot

- name: setup manager pip venv
  hosts: managers
  gather_facts: False
  become_user: "{{ builder }}"
  become: True
  tags: manager-venv

  roles:
    - vars
    - role: pip-venv
      venvs:
        - ansible
    - ansible
    - docker-compose
    - ca

- name: import site specific roles
  hosts: targets
  gather_facts: False
  tags: addon
  tasks:
    - name: load variables from parent vars directory
      include_vars: "{{ item }}"
      with_fileglob: "../../vars/*.yml"
    - include_tasks: "../../{{ addon_playbook }}"
      when: addon_playbook is defined
  roles:
    - reboot

- name: setup docker hosts
  hosts: targets
  gather_facts: False
  tags: setup-docker
  become: True

  roles:
    - vars
    - tls-certificate
    - docker
    - role: drbd
      when: drbd_master is defined
    - reboot

- name: setup manager user
  hosts: managers
  gather_facts: False
  become_user: "{{ builder }}"
  become: True
  tags: manager-user

  roles:
    - vars
    - role: tls-certificate
      become_user: root
      arg_tls_hostname: "{{ registry_fqdn }}"
    - manager
    - reboot

- name: build cluster
  hosts: targets
  gather_facts: False
  become: True
  tags: build-cluster

  roles:
    - vars
    - role: swarm
      when: swarm_master is defined
    - role: drbdmanage
      when: drbd_master is defined
- name: add drbd members
  serial: 1
  hosts: targets
  gather_facts: False
  become: True
  tags: build-cluster

  roles:
    - vars
    - role: drbdmanage-serial
      when: drbd_master is defined

- name: setup private registry
  hosts: managers
  gather_facts: False
  become_user: "{{ builder }}"
  become: True
  tags: registry

  roles:
    - vars
    - registry
    - role: awx
      when: install_awx | default(False)
